version: "3.7"
services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    depends_on:
    - service1
    - service2
    ports:
    - 80:8080
    - 443:8443
    - 19000:19000

  service1:
    image: jmalloc/echo-server
    hostname: service1

  service2:
    image: jmalloc/echo-server
    hostname: service2
