resources:
- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: example_proxy_cluster1
  type: STRICT_DNS
  load_assignment:
    cluster_name: example_proxy_cluster1
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: service1
              port_value: 8080
- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: example_proxy_cluster2
  type: STRICT_DNS
  load_assignment:
    cluster_name: example_proxy_cluster2
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: service2
              port_value: 8080